# Generated by Django 6.0.5 on 2026-06-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='123456', max_length=255),
            preserve_default=False,
        ),
    ]
