# Generated by Django 6.0.5 on 2026-06-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_address_zip'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='store_addressgnf',
        ),
    ]
