# Generated by Django 6.0.5 on 2026-06-06 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_address_table'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ('girish k r')
            """, """
            DELETE FROM store_collection
            WHERE title='girish k r'
            """)
    ]
