# Generated by Django 6.0.5 on 2026-06-07 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20260606_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='store.collection'),
        ),
    ]
