# Generated by Django 6.0.5 on 2026-06-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
    ]
