# Generated by Django 6.0.5 on 2026-06-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_collection_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
