# Generated by Django 6.0.7 on 2026-07-11 04:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='creted_date',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
