# Generated by Django 6.0.7 on 2026-07-16 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_customer_last_name_remove_customer_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        
        migrations.AddField(
            model_name='cartitem',
            name='itemprice',
            field=models.DecimalField(decimal_places=2, default=12.12, max_digits=6),
            preserve_default=False,
        ),
    
    ]
